[package]
name = "bits_rs"
version = "0.1.0"
edition = "2021"
description = "A library for working with bit sequences"
license = "MIT"
repository = "github.com/osh88/bits_rs"

[dependencies]
num = "0.4.0"
